ienpcs/ienpcs/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("gallery/", include("gallery.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ienpcs/gallery/models.py
import os
import uuid

from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

MAX_PARTY_SIZE = 6  # Maximum number of party slots used in party management


def web_image_with_hash(instance, filename):
    """Save name and location for npc portraits."""
    path = "web_portraits"
    fname, extension = os.path.splitext(filename)
    uuid_str = str(uuid.uuid4())
    format = fname + "_" + uuid_str + extension
    return os.path.join(path, format)


def zip_file_with_hash(instance, filename):
    """Save name and location for bmp pack zip files."""
    path = "zip_file"
    fname, extension = os.path.splitext(filename)
    uuid_str = str(uuid.uuid4())
    format = fname + "_" + uuid_str + extension
    return os.path.join(path, format)


def char_portrait_with_hash(instance, filename):
    """Save name and location for portrait web images."""
    path = "chars"
    fname, extension = os.path.splitext(filename)
    uuid_str = str(uuid.uuid4())
    format = fname + "_" + uuid_str + extension
    return os.path.join(path, format)


class Game(models.Model):
    """Model for IE games like BG1/2.

    Fields:
        short_name (str) - For use in menus, etc, like BG2:EE (where slug is bg2ee)
        order      (int) - Used for custom ordering in template and admin
    """

    name = models.CharField(max_length=50)
    slug = models.CharField(max_length=10)
    short_name = models.CharField(max_length=10)
    order = models.SmallIntegerField()
    title_screen = models.ImageField(upload_to="games", null=True)
    developer = models.CharField(max_length=100)
    release_year = models.SmallIntegerField()

    def __str__(self):
        return self.slug

    class Meta:
        ordering = ("order",)


class CharOrigin(models.TextChoices):
    """Enum for how a Character was created - Bioware(original), modder, beamdog."""

    OR = "OR", _("Original")
    MO = "MO", _("Mod")
    BE = "BE", _("Beamdog")


class PortraitOrigin(models.TextChoices):
    """Enum for origin of Portraits."""

    OR = "OR", _("Original")
    MO = "MO", _("Mod")
    BE = "BE", _("Beamdog")
    FA = "FA", _("Fanart")


class Character(models.Model):
    """Entry for character Portraits and lore, connected with multiple NPCs.

    Fields:
        slug    (str) - Used for urls
        img_170 (img) - Main image for the Character (TODO change name)
    """

    name = models.CharField(max_length=100)
    slug = models.SlugField()
    origin = models.CharField(
        max_length=2, choices=CharOrigin.choices, default=CharOrigin.OR
    )
    img_170 = models.ImageField(upload_to=char_portrait_with_hash)
    short_description = models.CharField(max_length=100, blank=True, default="")
    description = models.CharField(max_length=1000, blank=True, default="")

    def __str__(self):
        return f"{self.name}"

    class Meta:
        ordering = ("name",)


class InvitationCode(models.Model):
    """Invitation code to use at registration.

    Fields:
        code (str)     - The code itself
        note (str)     - Association, e.g. period, forum, etc.
        in_use (bool)  - Change to disable registrations before reacing max_uses
        max_uses (int) - Disable code upon reaching it
    """

    code = models.CharField(max_length=100)
    note = models.CharField(max_length=100, null=True, blank=True)
    in_use = models.BooleanField(default=True)
    max_uses = models.PositiveSmallIntegerField(default=20)
    times_used = models.PositiveSmallIntegerField(default=0)
    added = models.DateTimeField(default=timezone.now, blank=True)
    last_used = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ("added",)


class Link(models.Model):
    """Model for links on the Links page."""

    description = models.CharField(max_length=50)
    url = models.URLField()

    def __str__(self):
        return self.description

    class Meta:
        ordering = ("description",)


class Npc(models.Model):
    """Model for NPC, many-to-one for Character, many-to-many for Game.

    Fields:
        web_image (img)  - Small image to display on pages
        admin_note (str) - Note to serve as reminder of sorting, game allocation, etc
        adnd_class (str) - AD&D Class name, e.g. Fighter, Fighter/Mage
        race (str)       - AD&D Race or Sub-Race name, e.g. Elf, Drow, Winged Elf, with (M)/(F)
        alignment (str)  - Enum for AD&D Alignment
        str-cha (int)    - Attributes: Strength, Dexterity, Constitution, Intelligence, Wisdom, Charisma
        str_percentile (int) - 1-100, for Fighter type Classes, if str is 18, optional
        description (str)    - Short description, currently not shown anywhere
    """

    class Alignment(models.TextChoices):
        """Enum for AD&D aligments."""

        CG = "CG", _("Chaotic Good")
        NG = "NG", _("Neutral Good")
        LG = "LG", _("Lawful Good")
        CN = "CN", _("Chaotic Neutral")
        TN = "TN", _("True Neutral")
        LN = "LN", _("Lawful Neutral")
        CE = "CE", _("Chaotic Evil")
        NE = "NE", _("Neutral Evil")
        LE = "LE", _("Lawful Evil")
        UN = "UN", _("Unknown")

    web_image = models.ImageField(upload_to=web_image_with_hash, null=True)
    character = models.ForeignKey(Character, on_delete=models.CASCADE)
    game = models.ManyToManyField(Game, through="NpcInGame")
    name = models.CharField(max_length=100)
    admin_note = models.CharField(max_length=25, null=True, blank=True)
    adnd_class = models.CharField(max_length=25)
    race = models.CharField(max_length=20)
    alignment = models.CharField(
        max_length=2, choices=Alignment.choices, default=Alignment.UN
    )
    str = models.SmallIntegerField()
    str_percentile = models.SmallIntegerField(null=True, blank=True)
    dex = models.SmallIntegerField()
    con = models.SmallIntegerField()
    int = models.SmallIntegerField()
    wis = models.SmallIntegerField()
    cha = models.SmallIntegerField()
    description = models.CharField(max_length=500, blank=True, default="")

    def __str__(self):
        return f"{self.name} ({self.admin_note})"

    class Meta:
        ordering = ("name",)


class Portrait(models.Model):
    """Model for portraits in Character portrait galleries.

    Fields:
        origin (str)      - Enum for who created the image - original, beamdog, mod, fanart
        description (str) - Extra info about the image, not currently shown
        source (str)      - URL link to where the image was taken from, optional (none for original game art)
        web_image (img)   - Image to show on the website, should be losslessly compressed
        zip_file (zip)    - Optional, should be plain .zip file of .bmp files ready for use in games
    """

    character = models.ForeignKey(Character, null=True, on_delete=models.SET_NULL)
    origin = models.CharField(
        max_length=2, choices=PortraitOrigin.choices, default=PortraitOrigin.OR
    )
    description = models.CharField(max_length=200, blank=True, default="")
    source = models.URLField(blank=True, default="")
    created = models.DateTimeField(default=timezone.now, blank=True)
    web_image = models.ImageField(upload_to=web_image_with_hash)
    zip_file = models.FileField(upload_to=zip_file_with_hash, blank=True, null=True)

    def __str__(self):
        return f"{self.character.name} - {self.description[:20]}"

    class Meta:
        ordering = ("-created",)


class NpcInGame(models.Model):
    """Many-to-many relationship between Npc and Game, with extra field 'origin'."""

    game = models.ForeignKey(Game, null=True, on_delete=models.SET_NULL)
    npc = models.ForeignKey(Npc, null=True, on_delete=models.SET_NULL)
    origin = models.CharField(
        max_length=2, choices=CharOrigin.choices, default=CharOrigin.OR
    )

    def __str__(self):
        return f"{self.npc}  -  {self.game}"


class Party(models.Model):
    """Model to use for Party management.

    Created automatically upon user creation.

    Fields:
        user (fk)   - One party for one auth model user
        npcs (mtm)  - Up to 20 npcs to keep on a shortlist on Party page
        party_size (int) - Number of slots to use for party, user-settable, 1 to 6
    """

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    npcs = models.ManyToManyField(Npc, blank=True)
    party_size = models.PositiveSmallIntegerField(
        default=6, validators=[MaxValueValidator(MAX_PARTY_SIZE), MinValueValidator(1)]
    )

    def __str__(self):
        return f"{ self.user.username }"

    def save(self, *args, **kwargs):
        """Create 6 (MAX_PARTY_SIZE) slots upon Party creation."""
        is_new = self.pk is None
        super().save(*args, **kwargs)
        if is_new:
            for i in range(MAX_PARTY_SIZE):
                Slot.objects.create(party=self, position=i + 1)


def pc_portrait_path(instance, filename):
    """Path for saving user-uploaded image for user-created Pc."""
    path = "pcs"
    _, extension = os.path.splitext(filename)
    uuid_str = str(uuid.uuid4())
    new_filename = uuid_str + extension
    return os.path.join(path, new_filename)


class Pc(models.Model):
    """Model for user-created player characters.

    Fields:
        web_image (img) - Image of any dimensions, up to 100 KB file size
        adnd_class, race, alignment (str) - AD&D attributes, as for NPCs but more flexible
        str-cha (int)   - AD&D attributes, same as for NPCs
    """

    party = models.ForeignKey(Party, on_delete=models.CASCADE)
    web_image = models.ImageField(upload_to=pc_portrait_path, blank=True, null=True)
    name = models.CharField(max_length=30)
    adnd_class = models.CharField(

ienpcs/gallery/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User

from .models import Pc
from .validators import web_image_size


class AuthenticateUserForm(AuthenticationForm):
    """Form used for logging in."""

    class Meta:
        model = User
        fields = ("username", "password")


class ContactForm(forms.Form):
    """Form used to send an email to the site admin."""

    name = forms.CharField(max_length=80)
    email = forms.EmailField(required=False)
    message = forms.CharField(widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super(forms.Form, self).__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"


class CreatePcForm(forms.ModelForm):
    """Form used for creating and updating Player Characters for party."""

    class Meta:
        model = Pc
        fields = (
            "name",
            "web_image",
            "adnd_class",
            "race",
            "alignment",
            "str",
            "str_percentile",
            "dex",
            "con",
            "int",
            "wis",
            "cha",
        )

    def __init__(self, *args, **kwargs):
        super(forms.ModelForm, self).__init__(*args, **kwargs)

        help_text_dict = {
            "name": "Name is required.",
            "web_image": "Image should be 110x170px.",
            "adnd_class": "Ex: Fighter, Mage, F/M, Kensai/Illusionist/Swashbuckler",
            "race": "Ex: Human, Dwarf, Drow, Hamster",
            "alignment": "Ex: Neutral Good, Evil",
            "str": "Usually 3 to 18",
            "str_percentile": "For fighter classes, 1 to 100",
            "dex": "Usually 3 to 18",
            "con": "Usually 3 to 18",
            "int": "Usually 3 to 18",
            "wis": "Usually 3 to 18",
            "cha": "Usually 3 to 18",
        }

        label_dict = {
            "name": "Name",
            "web_image": "Portrait",
            "adnd_class": "Class",
            "race": "Race",
            "alignment": "Alignment",
            "str": "Strength",
            "str_percentile": "Str /100",
            "dex": "Dexterity",
            "con": "Constitution",
            "int": "Intelligence",
            "wis": "Wisdom",
            "cha": "Charisma",
        }

        # Add form-text to all fields from help_text_dict, add form-control, labels
        for field_key, field_value in self.fields.items():
            field_value.widget.attrs["class"] = "form-control"
            field_value.label = label_dict[field_key]
            help_str = f'<span class="form-text">{ help_text_dict[field_key] }</span>'
            field_value.help_text = help_str

        # Add custom validators
        self.fields["web_image"].validators.append(web_image_size)


class SignUpForm(UserCreationForm):
    """Form used for signing up new users."""

    invitation_code = forms.CharField(
        label="Invitation code:",
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "ex: 537b048d7f14e109c1b...",
            }
        ),
    )

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        help_text_dict = {
            "username": "Up to 150 characters. Letters, digits and @.+-_ only.",
            "email": "Enter a vaild email.",
            "password1": "PLACEHOLDER",  # Will be overridden
            "password2": "Enter the same password as before, for verification.",
        }

        label_dict = {
            "username": "Username",
            "email": "Email",
            "password1": "Password",
            "password2": "Confirm Password",
        }

        for field in ["username", "email", "password1", "password2"]:
            field_value = self.fields[field]
            field_value.widget.attrs["class"] = "form-control"
            field_value.widget.attrs["placeholder"] = "..."
            field_value.label = label_dict[field]
            help_str = (
                f'<span class="form-text text-muted">{ help_text_dict[field] }</span>'
            )
            field_value.help_text = help_str

        # Override parrword1 help text, differently styled by bootstrap
        self.fields["password1"].help_text = (
            '<ul class="form-text text-muted small">'
            "<li>Your password can't be too similar to your other personal information.</li>"
            "<li>Your password must contain at least 8 characters.</li>"
            "<li>Your password can't be a commonly used password.</li>"
            "<li>Your password can't be entirely numeric.</li>"
            "</ul>"
        )

ienpcs/gallery/templates/gallery/about.html
{% extends 'gallery/base.html' %}

{% block title %}
  <title>About</title>
{% endblock %}

{% block content %}
  <div class="container" style="max-width: 1150px;">
    <div class="row pt-5">
      <div class="col-12">
        <h2 class="border-bottom mb-4 pb-2"><a class="text-decoration-none" href="#">About</a></h2>
        <h4 class="pt-4">Purpose</h4>
        <p>The purpose of the website is to provide a convenient gallery for finding portraits specific to characters in the Infinity Engine games.</p>
        <h4 class="pt-4">Layout</h4>
        <p>In the Games page, you can find the different IE games and their different editions. Currently mod setups like BGTutu, BGT or EET are not included, as they retain the content of the games they modify. Different games and editions sometimes have different versions of the same character. For example Imoen the Thief in BG/BG:EE and Imoen the Thief/Mage in BG2/BG2:EE/BG:SoD. These versions are referred to as NPCs. On the individual game pages you can see a card with the NPC portrait and some information about them. They are sorted by being part of the original editions, being adde by Beamdog, and being added or made playable by modders.</p>
        <p>In the Characters section you can see a list of the characters that appear in any of the games. Some of the characters are from the original games, others are added in the enhanced editions, and some are brand new from mods. Details about the different versions that appeart in various games can be seen in the individual page of a character. This is also where the portrait gallery for the character is.</p>
        <p>The Links page has links to websites dedicated to the Infinity Engine games, including modding websites, forums, guides and galleries.</p>
        <h4 class="pt-4">Content</h4>
        <p>Currently the site has the original portraits from the games, art linked to mods and fanart.</p>
        <h4 class="pt-4">Contact</h4>
        <p>If you'd like to comment on the site or want to reach somebody regarding a game, npc, portrait, etc, please send a message!</p>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-6 py-3 rounded-2 bg-body-tertiary">
        <p>
          <strong>SMTP server needs to be configured. Please use github contact instead.</strong>
        </p>
        <form method="POST">
          {% csrf_token %}
          {{ form.as_p }}
          <button class="btn btn-secondary" type="submit">Send</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

ienpcs/gallery/templates/gallery/character_detail.html
{% extends 'gallery/base.html' %}

{% block title %}
  <title>{{ character.name }}</title>
{% endblock %}

{% block content %}
  <div class="container" style="max-width: 1150px;">
    <div class="row pt-5">
      <div class="col-12">
        <h2 class="border-bottom mb-4 pb-2"><a class="text-decoration-none" href="{% url 'gallery:character_list' %}">{{ character.name }}</a></h2>
        <div class="row">
          <div class="col-4">
            <p>{{ character.description }}</p>
            <br />
            <p>Character origin - {{ character.get_origin_display }}.</p>
          </div>
          <div class="col-8">
            {% comment %}Card that holds NPCs (portrait + attributes) related to Character{% endcomment %}
            <div class="card">
              <div class="card-header">
                <ul class="nav nav-tabs card-header-tabs" id="npc-in-game-list" role="tablist">
                  {% if npcs %}
                    {% for npc in npcs %}
                      <li class="nav-item">
                        {% comment %}if unignored django-formatter addon deletes "active" in forloop.first{% endcomment %}
                        {# prettier-ignore #}
                        <a class="nav-link {% if forloop.first %}active{% endif %}" href="#npc-v{{ forloop.counter }}" role="tab">
                        {% for game in npc.game.all %}
                          {{ game.short_name}}{% if not forloop.last %} - {% endif %}
                        {% endfor %}
                        </a>
                      </li>
                    {% endfor %}
                  {% else %}
                    <li class="nav-item">
                      <a class="nav-link active" href="#npc-v1" role="tab">No NPCs for this Character.</a>
                    </li>
                  {% endif %}
                </ul>
              </div>
              <div class="card-body">
                <div class="tab-content mt-3">
                  {% for npc in npcs %}
                    {% comment %}if unignored django-formatter addon deletes "active" in forloop.first{% endcomment %}
                    {# prettier-ignore #}
                    <div class="tab-pane {% if forloop.first %}active{% endif %}" id="npc-v{{ forloop.counter }}" role="tabpanel">

                      {% comment %}Table with stats{% endcomment %}
                      <div class="row">

                        <div class="col-3">
                          <img class="mb-2" src="{{ npc.web_image.url }}" alt="Portrait of {{ npc.name }}" />
                          {% if user.is_authenticated %}
                            <div class="card-subtitle mb-2 text-body-secondary"><small><a href="{% url 'gallery:party_add_npc' npc.id %}">Add to Party</a></small></div>
                          {% else %}
                            <div class="card-subtitle mb-2 text-body-tertiary"><small><a title="You must be logged in to manage Party">Add to Party</a></small></div>
                          {% endif %}
                        </div>

                        <div class="col-4">
                          <table class="table table-sm  table-borderless">
                            <tbody>
                              <tr>
                                <th scope="col" class="text-muted">Class</th>
                              </tr>
                              <tr>
                                <td>&nbsp;&nbsp;&nbsp;- {{ npc.adnd_class }}</td>
                              </tr>
                              <tr>
                                <th scope="col" class="text-muted">Alignment</th>
                              </tr>
                              <tr>
                                <td>&nbsp;&nbsp;&nbsp;- {{ npc.get_alignment_display }}</td>
                              </tr>
                              <tr>
                                <th scope="col" class="text-muted">Race</th>
                              </tr>
                              <tr>
                                <td>&nbsp;&nbsp;&nbsp;- {{ npc.race }}</td>
                              </tr>
                            </tbody>
                          </table>
                        </div>
                    
                        <div class="col-5">
                          <table class="table table-sm table-borderless">
                            <tbody>
                              <tr>
                                <th scope="row" class="col-6 text-muted">Strength</th>
                                <td>{{ npc.str }}{% if npc.str_percentile %}/{{ npc.str_percentile }}{% endif %}</td> 
                              </tr>
                              <tr>
                                <th scope="row" class="text-muted">Dexterity</th>
                                <td>{{ npc.dex }}</td>
                              </tr>
                              <tr>
                                <th scope="row" class="text-muted">Constitution</th>
                                <td>{{ npc.con }}</td>
                              </tr>
                              <tr>
                                <th scope="row" class="text-muted">Intelligence</th>
                                <td>{{ npc.int }}</td>
                              </tr>
                              <tr>
                                <th scope="row" class="text-muted">Wisdom</th>
                                <td>{{ npc.wis }}</td>
                              </tr>
                              <tr>
                                <th scope="row" class="text-muted">Charisma</th>
                                <td>{{ npc.cha }}</td>
                              </tr>
                            </tbody>
                          </table>
                        </div>

                      </div>
                      {% comment %} <a href="#" class="btn btn-secondary btn-sm">Button</a> {% endcomment %}

                    </div>
                  {% endfor %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="portraitGrid" class="container mt-4 pb-5 shadow-sm bg-body-tertiary" style="max-width: 1150px;">
      <div class="row px-4 pt-5">
        <div class="col-12">
          <h4 class="border-bottom mb-4 pb-2">Portraits</h4>
        </div>
      </div>

      <div class="row justify-content-center">
        {% comment %}Portraits for the character with soruce and optionally bmp zip{% endcomment %}
        {% for pt in character.portrait_set.all %}
          <div class="col-auto mb-4">
            <div class="card h-100" style="width: 212px;">
              <a href="#"><img src="{{ pt.web_image.url }}" class="card-img-top" width="210" height="330" alt="A character portrait" /></a>
              <div class="card-body">
                <p class="card-text">{{ pt.get_origin_display }} - {{ pt.description }}</p>
              </div>
              <div class="card-footer">
                <small class="text-body-secondary"><a href="{{ pt.source }}">Source</a></small>
                {% if pt.zip_file %}
                  |
                  <small class="text-body-secondary"><a href="{{ pt.zip_file.url }}">Zip file</a></small>
                {% endif %}
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>

  <script>
    // Switch to selected tab
    document.addEventListener('DOMContentLoaded', function () {
      var tabs = document.querySelectorAll('#npc-in-game-list a')
      tabs.forEach(function (tab) {
        tab.addEventListener('click', function (e) {
          e.preventDefault()
          var id = this.getAttribute('href')
          // Remove active class from all tabs
          tabs.forEach(function (tab) {
            tab.classList.remove('active')
            document.querySelector(tab.getAttribute('href')).classList.remove('active')
          })
          // Add active class to clicked tab and corresponding tab pane
          this.classList.add('active')
          document.querySelector(id).classList.add('active')
        })
      })
    })
  </script>
{% endblock %}

ienpcs/gallery/templates/gallery/game_detail.html
{% extends 'gallery/base.html' %}

{% block title %}
  <title>{{ game.name }}</title>
{% endblock %}

{% block content %}
  <div class="container" style="max-width: 1150px;">
    <div class="row pt-5">
      <div class="col-12">
        <h2 class="border-bottom mb-4 pb-2"><a class="text-decoration-none" href="{% url 'gallery:game_list' %}">{{ game.name }}</a></h2>
        <p>{{ game.description }}</p>
      </div>
    </div>

    <div class="container mt-4 pb-5 shadow-sm bg-body-tertiary">
      {% comment %}Outer loop for Original/Beamdog/Mod categories{% endcomment %}
      {% for origin, npc_in_game_qset in origin_dict.items %}
        <div class="row px-4 pt-5">
          <div class="col-12">
            <h3 class="border-bottom mb-4 pb-2">{{ origin }} NPCs ({{ npc_in_game_qset.count }})</h3>
          </div>
        </div>
        <div class="row justify-content-center">
          {% for npc_in_game in npc_in_game_qset %}
            <div class="col-auto mb-3">
              <div class="card h-100" style="width: 20rem;">
                <div class="row g-0">
                  <div class="col" style="max-width: 120px;">
                    <img src="{{ npc_in_game.npc.web_image.url }}" width="110" height="170" class="rounded-start" alt="..." />
                  </div>
                  <div class="col">
                    <div class="card-body p-2">
                      <h5 class="card-title">{{ npc_in_game.npc.name }}</h5>
                      <h6 class="card-subtitle mb-2 text-body-secondary">{{ npc_in_game.npc.adnd_class }}</h6>
                      <h6 class="card-subtitle mb-2 text-body-secondary">{{ npc_in_game.npc.race }}</h6>
                      <h6 class="card-subtitle mb-2 text-body-secondary">{{ npc_in_game.npc.get_alignment_display }}</h6>
                      {% if user.is_authenticated %}
                        <h6 class="card-subtitle mb-2 text-body-secondary"><small><a href="{% url 'gallery:party_add_npc' npc_in_game.npc.id %}">Add to Party</a></small></h6>
                      {% else %}
                        <h6 class="card-subtitle mb-2 text-body-tertiary"><small><a title="You must be logged in to manage Party">Add to Party</a></small></h6>
                      {% endif %}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

ienpcs/gallery/templates/gallery/game_list.html
{% extends 'gallery/base.html' %}

{% block title %}
  <title>Games</title>
{% endblock %}

{% block content %}
  <div id="gameGrid" class="container mt-4 pb-5" style="max-width: 1150px;">
    {% comment %}Row with snort names for navigation.{% endcomment %}
    <ul class="nav nav-underline justify-content-center">
      {% for game in game_list %}
        <li class="nav-item border-bottom">
          <a class="nav-link" href="{% url 'gallery:game_detail' game.slug %}">{{ game.short_name }}</a>
        </li>
      {% endfor %}
    </ul>

    {% for game in game_list %}
      <div class="row pt-5">
        <div class="col-12">
          <h4 class="border-bottom mb-4 pb-2"><a class="text-decoration-none fw-bold" href="{% url 'gallery:game_detail' game.slug %}">{{ game.name }}</a></h4>
        </div>
      </div>
      <div class="row">
        <div class="col-4" style="min-width: 350px;">
          <a href="{% url 'gallery:game_detail' game.slug %}"><img src="{{ game.title_screen.url }}" class="border border-3 mb-3" alt="Game title screen for {{ game.name }}" /></a>
        </div>
        <div class="col-8" style="min-width: 25rem;">
          <table class="table table-striped">
            <tbody>
              <tr>
                <th class="col-3 text-muted" scope="row">Developer</th>
                <td class="col-9">{{ game.developer }}</td>
              </tr>
              <tr>
                <th class="text-muted" scope="row">Release</th>
                <td>{{ game.release_year }}</td>
              </tr>
              <tr>
                <th class="border-bottom-0 text-muted" scope="row">NPCs (incl. mods)</th>
                <td class="border-bottom-0 pe-4">
                  {% for npc in game.npc_set.all %}
                    {{ npc.name }}{% if not forloop.last %}, {% endif %}
                    {% empty %}No NPCs for this game.
                  {% endfor %}
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

ienpcs/gallery/templates/gallery/index.html
{% extends 'gallery/base.html' %}

{% block title %}
  <title>Games</title>
{% endblock %}

{% block content %}
  {% for game in game_list %}
    <p>{{ game.name }}</p>
    {% for npc in game.npc_set.all %}
      {{ npc.name }} |
    {% endfor %}
  {% endfor %}
{% endblock %}